package com.circle.dao;

import com.circle.vo.TeAccountRole;
import com.circle.vo.TeAccountRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeAccountRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account_role
     *
     * @mbggenerated
     */
    int countByExample(TeAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account_role
     *
     * @mbggenerated
     */
    int deleteByExample(TeAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long aoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account_role
     *
     * @mbggenerated
     */
    int insert(TeAccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account_role
     *
     * @mbggenerated
     */
    int insertSelective(TeAccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account_role
     *
     * @mbggenerated
     */
    List<TeAccountRole> selectByExample(TeAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account_role
     *
     * @mbggenerated
     */
    TeAccountRole selectByPrimaryKey(Long aoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TeAccountRole record, @Param("example") TeAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TeAccountRole record, @Param("example") TeAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TeAccountRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TeAccountRole record);
}