package com.circle.dao;

import com.circle.vo.TeRole;
import com.circle.vo.TeRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_role
     *
     * @mbggenerated
     */
    int countByExample(TeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_role
     *
     * @mbggenerated
     */
    int deleteByExample(TeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_role
     *
     * @mbggenerated
     */
    int insert(TeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_role
     *
     * @mbggenerated
     */
    int insertSelective(TeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_role
     *
     * @mbggenerated
     */
    List<TeRole> selectByExample(TeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_role
     *
     * @mbggenerated
     */
    TeRole selectByPrimaryKey(Long roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TeRole record, @Param("example") TeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TeRole record, @Param("example") TeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TeRole record);
}