package com.circle.dao;

import com.circle.vo.TeTest;
import com.circle.vo.TeTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_test
     *
     * @mbggenerated
     */
    int countByExample(TeTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_test
     *
     * @mbggenerated
     */
    int deleteByExample(TeTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_test
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_test
     *
     * @mbggenerated
     */
    int insert(TeTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_test
     *
     * @mbggenerated
     */
    int insertSelective(TeTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_test
     *
     * @mbggenerated
     */
    List<TeTest> selectByExample(TeTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_test
     *
     * @mbggenerated
     */
    TeTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_test
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TeTest record, @Param("example") TeTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_test
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TeTest record, @Param("example") TeTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_test
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TeTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_test
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TeTest record);
}