package com.circle.dao;

import com.circle.vo.WebSite;
import com.circle.vo.WebSiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebSiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_site
     *
     * @mbggenerated
     */
    int countByExample(WebSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_site
     *
     * @mbggenerated
     */
    int deleteByExample(WebSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_site
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_site
     *
     * @mbggenerated
     */
    int insert(WebSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_site
     *
     * @mbggenerated
     */
    int insertSelective(WebSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_site
     *
     * @mbggenerated
     */
    List<WebSite> selectByExample(WebSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_site
     *
     * @mbggenerated
     */
    WebSite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_site
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WebSite record, @Param("example") WebSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_site
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WebSite record, @Param("example") WebSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_site
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WebSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_site
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WebSite record);
}