package com.circle.vo;

import java.util.Date;

public class TeAccountRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_account_role.aoId
     *
     * @mbggenerated
     */
    private Long aoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_account_role.acctName
     *
     * @mbggenerated
     */
    private String acctname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_account_role.roleLabel
     *
     * @mbggenerated
     */
    private String rolelabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_account_role.timestamp
     *
     * @mbggenerated
     */
    private Date timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_account_role.aoId
     *
     * @return the value of te_account_role.aoId
     *
     * @mbggenerated
     */
    public Long getAoid() {
        return aoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_account_role.aoId
     *
     * @param aoid the value for te_account_role.aoId
     *
     * @mbggenerated
     */
    public void setAoid(Long aoid) {
        this.aoid = aoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_account_role.acctName
     *
     * @return the value of te_account_role.acctName
     *
     * @mbggenerated
     */
    public String getAcctname() {
        return acctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_account_role.acctName
     *
     * @param acctname the value for te_account_role.acctName
     *
     * @mbggenerated
     */
    public void setAcctname(String acctname) {
        this.acctname = acctname == null ? null : acctname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_account_role.roleLabel
     *
     * @return the value of te_account_role.roleLabel
     *
     * @mbggenerated
     */
    public String getRolelabel() {
        return rolelabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_account_role.roleLabel
     *
     * @param rolelabel the value for te_account_role.roleLabel
     *
     * @mbggenerated
     */
    public void setRolelabel(String rolelabel) {
        this.rolelabel = rolelabel == null ? null : rolelabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_account_role.timestamp
     *
     * @return the value of te_account_role.timestamp
     *
     * @mbggenerated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_account_role.timestamp
     *
     * @param timestamp the value for te_account_role.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}