package com.circle.vo;

import java.util.Date;

public class TeAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_account.acctId
     *
     * @mbggenerated
     */
    private Long acctid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_account.acctName
     *
     * @mbggenerated
     */
    private String acctname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_account.acctNickname
     *
     * @mbggenerated
     */
    private String acctnickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_account.acctPassword
     *
     * @mbggenerated
     */
    private String acctpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_account.acctState
     *
     * @mbggenerated
     */
    private Integer acctstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_account.acctSuper
     *
     * @mbggenerated
     */
    private Boolean acctsuper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_account.acctDeleteState
     *
     * @mbggenerated
     */
    private Boolean acctdeletestate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_account.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_account.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_account.timestamp
     *
     * @mbggenerated
     */
    private Date timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_account.acctId
     *
     * @return the value of te_account.acctId
     *
     * @mbggenerated
     */
    public Long getAcctid() {
        return acctid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_account.acctId
     *
     * @param acctid the value for te_account.acctId
     *
     * @mbggenerated
     */
    public void setAcctid(Long acctid) {
        this.acctid = acctid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_account.acctName
     *
     * @return the value of te_account.acctName
     *
     * @mbggenerated
     */
    public String getAcctname() {
        return acctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_account.acctName
     *
     * @param acctname the value for te_account.acctName
     *
     * @mbggenerated
     */
    public void setAcctname(String acctname) {
        this.acctname = acctname == null ? null : acctname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_account.acctNickname
     *
     * @return the value of te_account.acctNickname
     *
     * @mbggenerated
     */
    public String getAcctnickname() {
        return acctnickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_account.acctNickname
     *
     * @param acctnickname the value for te_account.acctNickname
     *
     * @mbggenerated
     */
    public void setAcctnickname(String acctnickname) {
        this.acctnickname = acctnickname == null ? null : acctnickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_account.acctPassword
     *
     * @return the value of te_account.acctPassword
     *
     * @mbggenerated
     */
    public String getAcctpassword() {
        return acctpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_account.acctPassword
     *
     * @param acctpassword the value for te_account.acctPassword
     *
     * @mbggenerated
     */
    public void setAcctpassword(String acctpassword) {
        this.acctpassword = acctpassword == null ? null : acctpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_account.acctState
     *
     * @return the value of te_account.acctState
     *
     * @mbggenerated
     */
    public Integer getAcctstate() {
        return acctstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_account.acctState
     *
     * @param acctstate the value for te_account.acctState
     *
     * @mbggenerated
     */
    public void setAcctstate(Integer acctstate) {
        this.acctstate = acctstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_account.acctSuper
     *
     * @return the value of te_account.acctSuper
     *
     * @mbggenerated
     */
    public Boolean getAcctsuper() {
        return acctsuper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_account.acctSuper
     *
     * @param acctsuper the value for te_account.acctSuper
     *
     * @mbggenerated
     */
    public void setAcctsuper(Boolean acctsuper) {
        this.acctsuper = acctsuper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_account.acctDeleteState
     *
     * @return the value of te_account.acctDeleteState
     *
     * @mbggenerated
     */
    public Boolean getAcctdeletestate() {
        return acctdeletestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_account.acctDeleteState
     *
     * @param acctdeletestate the value for te_account.acctDeleteState
     *
     * @mbggenerated
     */
    public void setAcctdeletestate(Boolean acctdeletestate) {
        this.acctdeletestate = acctdeletestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_account.createTime
     *
     * @return the value of te_account.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_account.createTime
     *
     * @param createtime the value for te_account.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_account.creator
     *
     * @return the value of te_account.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_account.creator
     *
     * @param creator the value for te_account.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_account.timestamp
     *
     * @return the value of te_account.timestamp
     *
     * @mbggenerated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_account.timestamp
     *
     * @param timestamp the value for te_account.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}