package com.circle.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TeAccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table te_account
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table te_account
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table te_account
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account
     *
     * @mbggenerated
     */
    public TeAccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_account
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table te_account
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAcctidIsNull() {
            addCriterion("acctId is null");
            return (Criteria) this;
        }

        public Criteria andAcctidIsNotNull() {
            addCriterion("acctId is not null");
            return (Criteria) this;
        }

        public Criteria andAcctidEqualTo(Long value) {
            addCriterion("acctId =", value, "acctid");
            return (Criteria) this;
        }

        public Criteria andAcctidNotEqualTo(Long value) {
            addCriterion("acctId <>", value, "acctid");
            return (Criteria) this;
        }

        public Criteria andAcctidGreaterThan(Long value) {
            addCriterion("acctId >", value, "acctid");
            return (Criteria) this;
        }

        public Criteria andAcctidGreaterThanOrEqualTo(Long value) {
            addCriterion("acctId >=", value, "acctid");
            return (Criteria) this;
        }

        public Criteria andAcctidLessThan(Long value) {
            addCriterion("acctId <", value, "acctid");
            return (Criteria) this;
        }

        public Criteria andAcctidLessThanOrEqualTo(Long value) {
            addCriterion("acctId <=", value, "acctid");
            return (Criteria) this;
        }

        public Criteria andAcctidIn(List<Long> values) {
            addCriterion("acctId in", values, "acctid");
            return (Criteria) this;
        }

        public Criteria andAcctidNotIn(List<Long> values) {
            addCriterion("acctId not in", values, "acctid");
            return (Criteria) this;
        }

        public Criteria andAcctidBetween(Long value1, Long value2) {
            addCriterion("acctId between", value1, value2, "acctid");
            return (Criteria) this;
        }

        public Criteria andAcctidNotBetween(Long value1, Long value2) {
            addCriterion("acctId not between", value1, value2, "acctid");
            return (Criteria) this;
        }

        public Criteria andAcctnameIsNull() {
            addCriterion("acctName is null");
            return (Criteria) this;
        }

        public Criteria andAcctnameIsNotNull() {
            addCriterion("acctName is not null");
            return (Criteria) this;
        }

        public Criteria andAcctnameEqualTo(String value) {
            addCriterion("acctName =", value, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameNotEqualTo(String value) {
            addCriterion("acctName <>", value, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameGreaterThan(String value) {
            addCriterion("acctName >", value, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameGreaterThanOrEqualTo(String value) {
            addCriterion("acctName >=", value, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameLessThan(String value) {
            addCriterion("acctName <", value, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameLessThanOrEqualTo(String value) {
            addCriterion("acctName <=", value, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameLike(String value) {
            addCriterion("acctName like", value, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameNotLike(String value) {
            addCriterion("acctName not like", value, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameIn(List<String> values) {
            addCriterion("acctName in", values, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameNotIn(List<String> values) {
            addCriterion("acctName not in", values, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameBetween(String value1, String value2) {
            addCriterion("acctName between", value1, value2, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnameNotBetween(String value1, String value2) {
            addCriterion("acctName not between", value1, value2, "acctname");
            return (Criteria) this;
        }

        public Criteria andAcctnicknameIsNull() {
            addCriterion("acctNickname is null");
            return (Criteria) this;
        }

        public Criteria andAcctnicknameIsNotNull() {
            addCriterion("acctNickname is not null");
            return (Criteria) this;
        }

        public Criteria andAcctnicknameEqualTo(String value) {
            addCriterion("acctNickname =", value, "acctnickname");
            return (Criteria) this;
        }

        public Criteria andAcctnicknameNotEqualTo(String value) {
            addCriterion("acctNickname <>", value, "acctnickname");
            return (Criteria) this;
        }

        public Criteria andAcctnicknameGreaterThan(String value) {
            addCriterion("acctNickname >", value, "acctnickname");
            return (Criteria) this;
        }

        public Criteria andAcctnicknameGreaterThanOrEqualTo(String value) {
            addCriterion("acctNickname >=", value, "acctnickname");
            return (Criteria) this;
        }

        public Criteria andAcctnicknameLessThan(String value) {
            addCriterion("acctNickname <", value, "acctnickname");
            return (Criteria) this;
        }

        public Criteria andAcctnicknameLessThanOrEqualTo(String value) {
            addCriterion("acctNickname <=", value, "acctnickname");
            return (Criteria) this;
        }

        public Criteria andAcctnicknameLike(String value) {
            addCriterion("acctNickname like", value, "acctnickname");
            return (Criteria) this;
        }

        public Criteria andAcctnicknameNotLike(String value) {
            addCriterion("acctNickname not like", value, "acctnickname");
            return (Criteria) this;
        }

        public Criteria andAcctnicknameIn(List<String> values) {
            addCriterion("acctNickname in", values, "acctnickname");
            return (Criteria) this;
        }

        public Criteria andAcctnicknameNotIn(List<String> values) {
            addCriterion("acctNickname not in", values, "acctnickname");
            return (Criteria) this;
        }

        public Criteria andAcctnicknameBetween(String value1, String value2) {
            addCriterion("acctNickname between", value1, value2, "acctnickname");
            return (Criteria) this;
        }

        public Criteria andAcctnicknameNotBetween(String value1, String value2) {
            addCriterion("acctNickname not between", value1, value2, "acctnickname");
            return (Criteria) this;
        }

        public Criteria andAcctpasswordIsNull() {
            addCriterion("acctPassword is null");
            return (Criteria) this;
        }

        public Criteria andAcctpasswordIsNotNull() {
            addCriterion("acctPassword is not null");
            return (Criteria) this;
        }

        public Criteria andAcctpasswordEqualTo(String value) {
            addCriterion("acctPassword =", value, "acctpassword");
            return (Criteria) this;
        }

        public Criteria andAcctpasswordNotEqualTo(String value) {
            addCriterion("acctPassword <>", value, "acctpassword");
            return (Criteria) this;
        }

        public Criteria andAcctpasswordGreaterThan(String value) {
            addCriterion("acctPassword >", value, "acctpassword");
            return (Criteria) this;
        }

        public Criteria andAcctpasswordGreaterThanOrEqualTo(String value) {
            addCriterion("acctPassword >=", value, "acctpassword");
            return (Criteria) this;
        }

        public Criteria andAcctpasswordLessThan(String value) {
            addCriterion("acctPassword <", value, "acctpassword");
            return (Criteria) this;
        }

        public Criteria andAcctpasswordLessThanOrEqualTo(String value) {
            addCriterion("acctPassword <=", value, "acctpassword");
            return (Criteria) this;
        }

        public Criteria andAcctpasswordLike(String value) {
            addCriterion("acctPassword like", value, "acctpassword");
            return (Criteria) this;
        }

        public Criteria andAcctpasswordNotLike(String value) {
            addCriterion("acctPassword not like", value, "acctpassword");
            return (Criteria) this;
        }

        public Criteria andAcctpasswordIn(List<String> values) {
            addCriterion("acctPassword in", values, "acctpassword");
            return (Criteria) this;
        }

        public Criteria andAcctpasswordNotIn(List<String> values) {
            addCriterion("acctPassword not in", values, "acctpassword");
            return (Criteria) this;
        }

        public Criteria andAcctpasswordBetween(String value1, String value2) {
            addCriterion("acctPassword between", value1, value2, "acctpassword");
            return (Criteria) this;
        }

        public Criteria andAcctpasswordNotBetween(String value1, String value2) {
            addCriterion("acctPassword not between", value1, value2, "acctpassword");
            return (Criteria) this;
        }

        public Criteria andAcctstateIsNull() {
            addCriterion("acctState is null");
            return (Criteria) this;
        }

        public Criteria andAcctstateIsNotNull() {
            addCriterion("acctState is not null");
            return (Criteria) this;
        }

        public Criteria andAcctstateEqualTo(Integer value) {
            addCriterion("acctState =", value, "acctstate");
            return (Criteria) this;
        }

        public Criteria andAcctstateNotEqualTo(Integer value) {
            addCriterion("acctState <>", value, "acctstate");
            return (Criteria) this;
        }

        public Criteria andAcctstateGreaterThan(Integer value) {
            addCriterion("acctState >", value, "acctstate");
            return (Criteria) this;
        }

        public Criteria andAcctstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("acctState >=", value, "acctstate");
            return (Criteria) this;
        }

        public Criteria andAcctstateLessThan(Integer value) {
            addCriterion("acctState <", value, "acctstate");
            return (Criteria) this;
        }

        public Criteria andAcctstateLessThanOrEqualTo(Integer value) {
            addCriterion("acctState <=", value, "acctstate");
            return (Criteria) this;
        }

        public Criteria andAcctstateIn(List<Integer> values) {
            addCriterion("acctState in", values, "acctstate");
            return (Criteria) this;
        }

        public Criteria andAcctstateNotIn(List<Integer> values) {
            addCriterion("acctState not in", values, "acctstate");
            return (Criteria) this;
        }

        public Criteria andAcctstateBetween(Integer value1, Integer value2) {
            addCriterion("acctState between", value1, value2, "acctstate");
            return (Criteria) this;
        }

        public Criteria andAcctstateNotBetween(Integer value1, Integer value2) {
            addCriterion("acctState not between", value1, value2, "acctstate");
            return (Criteria) this;
        }

        public Criteria andAcctsuperIsNull() {
            addCriterion("acctSuper is null");
            return (Criteria) this;
        }

        public Criteria andAcctsuperIsNotNull() {
            addCriterion("acctSuper is not null");
            return (Criteria) this;
        }

        public Criteria andAcctsuperEqualTo(Boolean value) {
            addCriterion("acctSuper =", value, "acctsuper");
            return (Criteria) this;
        }

        public Criteria andAcctsuperNotEqualTo(Boolean value) {
            addCriterion("acctSuper <>", value, "acctsuper");
            return (Criteria) this;
        }

        public Criteria andAcctsuperGreaterThan(Boolean value) {
            addCriterion("acctSuper >", value, "acctsuper");
            return (Criteria) this;
        }

        public Criteria andAcctsuperGreaterThanOrEqualTo(Boolean value) {
            addCriterion("acctSuper >=", value, "acctsuper");
            return (Criteria) this;
        }

        public Criteria andAcctsuperLessThan(Boolean value) {
            addCriterion("acctSuper <", value, "acctsuper");
            return (Criteria) this;
        }

        public Criteria andAcctsuperLessThanOrEqualTo(Boolean value) {
            addCriterion("acctSuper <=", value, "acctsuper");
            return (Criteria) this;
        }

        public Criteria andAcctsuperIn(List<Boolean> values) {
            addCriterion("acctSuper in", values, "acctsuper");
            return (Criteria) this;
        }

        public Criteria andAcctsuperNotIn(List<Boolean> values) {
            addCriterion("acctSuper not in", values, "acctsuper");
            return (Criteria) this;
        }

        public Criteria andAcctsuperBetween(Boolean value1, Boolean value2) {
            addCriterion("acctSuper between", value1, value2, "acctsuper");
            return (Criteria) this;
        }

        public Criteria andAcctsuperNotBetween(Boolean value1, Boolean value2) {
            addCriterion("acctSuper not between", value1, value2, "acctsuper");
            return (Criteria) this;
        }

        public Criteria andAcctdeletestateIsNull() {
            addCriterion("acctDeleteState is null");
            return (Criteria) this;
        }

        public Criteria andAcctdeletestateIsNotNull() {
            addCriterion("acctDeleteState is not null");
            return (Criteria) this;
        }

        public Criteria andAcctdeletestateEqualTo(Boolean value) {
            addCriterion("acctDeleteState =", value, "acctdeletestate");
            return (Criteria) this;
        }

        public Criteria andAcctdeletestateNotEqualTo(Boolean value) {
            addCriterion("acctDeleteState <>", value, "acctdeletestate");
            return (Criteria) this;
        }

        public Criteria andAcctdeletestateGreaterThan(Boolean value) {
            addCriterion("acctDeleteState >", value, "acctdeletestate");
            return (Criteria) this;
        }

        public Criteria andAcctdeletestateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("acctDeleteState >=", value, "acctdeletestate");
            return (Criteria) this;
        }

        public Criteria andAcctdeletestateLessThan(Boolean value) {
            addCriterion("acctDeleteState <", value, "acctdeletestate");
            return (Criteria) this;
        }

        public Criteria andAcctdeletestateLessThanOrEqualTo(Boolean value) {
            addCriterion("acctDeleteState <=", value, "acctdeletestate");
            return (Criteria) this;
        }

        public Criteria andAcctdeletestateIn(List<Boolean> values) {
            addCriterion("acctDeleteState in", values, "acctdeletestate");
            return (Criteria) this;
        }

        public Criteria andAcctdeletestateNotIn(List<Boolean> values) {
            addCriterion("acctDeleteState not in", values, "acctdeletestate");
            return (Criteria) this;
        }

        public Criteria andAcctdeletestateBetween(Boolean value1, Boolean value2) {
            addCriterion("acctDeleteState between", value1, value2, "acctdeletestate");
            return (Criteria) this;
        }

        public Criteria andAcctdeletestateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("acctDeleteState not between", value1, value2, "acctdeletestate");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNull() {
            addCriterion("timestamp is null");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNotNull() {
            addCriterion("timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampEqualTo(Date value) {
            addCriterion("timestamp =", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotEqualTo(Date value) {
            addCriterion("timestamp <>", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThan(Date value) {
            addCriterion("timestamp >", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("timestamp >=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThan(Date value) {
            addCriterion("timestamp <", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThanOrEqualTo(Date value) {
            addCriterion("timestamp <=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampIn(List<Date> values) {
            addCriterion("timestamp in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotIn(List<Date> values) {
            addCriterion("timestamp not in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampBetween(Date value1, Date value2) {
            addCriterion("timestamp between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotBetween(Date value1, Date value2) {
            addCriterion("timestamp not between", value1, value2, "timestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table te_account
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table te_account
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}