package com.circle.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TeModuleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table te_module
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table te_module
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table te_module
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_module
     *
     * @mbggenerated
     */
    public TeModuleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_module
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_module
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_module
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_module
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_module
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_module
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_module
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_module
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_module
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table te_module
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table te_module
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andModuleidIsNull() {
            addCriterion("moduleId is null");
            return (Criteria) this;
        }

        public Criteria andModuleidIsNotNull() {
            addCriterion("moduleId is not null");
            return (Criteria) this;
        }

        public Criteria andModuleidEqualTo(Long value) {
            addCriterion("moduleId =", value, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidNotEqualTo(Long value) {
            addCriterion("moduleId <>", value, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidGreaterThan(Long value) {
            addCriterion("moduleId >", value, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidGreaterThanOrEqualTo(Long value) {
            addCriterion("moduleId >=", value, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidLessThan(Long value) {
            addCriterion("moduleId <", value, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidLessThanOrEqualTo(Long value) {
            addCriterion("moduleId <=", value, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidIn(List<Long> values) {
            addCriterion("moduleId in", values, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidNotIn(List<Long> values) {
            addCriterion("moduleId not in", values, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidBetween(Long value1, Long value2) {
            addCriterion("moduleId between", value1, value2, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModuleidNotBetween(Long value1, Long value2) {
            addCriterion("moduleId not between", value1, value2, "moduleid");
            return (Criteria) this;
        }

        public Criteria andModulenameIsNull() {
            addCriterion("moduleName is null");
            return (Criteria) this;
        }

        public Criteria andModulenameIsNotNull() {
            addCriterion("moduleName is not null");
            return (Criteria) this;
        }

        public Criteria andModulenameEqualTo(String value) {
            addCriterion("moduleName =", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameNotEqualTo(String value) {
            addCriterion("moduleName <>", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameGreaterThan(String value) {
            addCriterion("moduleName >", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameGreaterThanOrEqualTo(String value) {
            addCriterion("moduleName >=", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameLessThan(String value) {
            addCriterion("moduleName <", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameLessThanOrEqualTo(String value) {
            addCriterion("moduleName <=", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameLike(String value) {
            addCriterion("moduleName like", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameNotLike(String value) {
            addCriterion("moduleName not like", value, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameIn(List<String> values) {
            addCriterion("moduleName in", values, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameNotIn(List<String> values) {
            addCriterion("moduleName not in", values, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameBetween(String value1, String value2) {
            addCriterion("moduleName between", value1, value2, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulenameNotBetween(String value1, String value2) {
            addCriterion("moduleName not between", value1, value2, "modulename");
            return (Criteria) this;
        }

        public Criteria andModulecodeIsNull() {
            addCriterion("moduleCode is null");
            return (Criteria) this;
        }

        public Criteria andModulecodeIsNotNull() {
            addCriterion("moduleCode is not null");
            return (Criteria) this;
        }

        public Criteria andModulecodeEqualTo(String value) {
            addCriterion("moduleCode =", value, "modulecode");
            return (Criteria) this;
        }

        public Criteria andModulecodeNotEqualTo(String value) {
            addCriterion("moduleCode <>", value, "modulecode");
            return (Criteria) this;
        }

        public Criteria andModulecodeGreaterThan(String value) {
            addCriterion("moduleCode >", value, "modulecode");
            return (Criteria) this;
        }

        public Criteria andModulecodeGreaterThanOrEqualTo(String value) {
            addCriterion("moduleCode >=", value, "modulecode");
            return (Criteria) this;
        }

        public Criteria andModulecodeLessThan(String value) {
            addCriterion("moduleCode <", value, "modulecode");
            return (Criteria) this;
        }

        public Criteria andModulecodeLessThanOrEqualTo(String value) {
            addCriterion("moduleCode <=", value, "modulecode");
            return (Criteria) this;
        }

        public Criteria andModulecodeLike(String value) {
            addCriterion("moduleCode like", value, "modulecode");
            return (Criteria) this;
        }

        public Criteria andModulecodeNotLike(String value) {
            addCriterion("moduleCode not like", value, "modulecode");
            return (Criteria) this;
        }

        public Criteria andModulecodeIn(List<String> values) {
            addCriterion("moduleCode in", values, "modulecode");
            return (Criteria) this;
        }

        public Criteria andModulecodeNotIn(List<String> values) {
            addCriterion("moduleCode not in", values, "modulecode");
            return (Criteria) this;
        }

        public Criteria andModulecodeBetween(String value1, String value2) {
            addCriterion("moduleCode between", value1, value2, "modulecode");
            return (Criteria) this;
        }

        public Criteria andModulecodeNotBetween(String value1, String value2) {
            addCriterion("moduleCode not between", value1, value2, "modulecode");
            return (Criteria) this;
        }

        public Criteria andModulesupercodeIsNull() {
            addCriterion("moduleSuperCode is null");
            return (Criteria) this;
        }

        public Criteria andModulesupercodeIsNotNull() {
            addCriterion("moduleSuperCode is not null");
            return (Criteria) this;
        }

        public Criteria andModulesupercodeEqualTo(String value) {
            addCriterion("moduleSuperCode =", value, "modulesupercode");
            return (Criteria) this;
        }

        public Criteria andModulesupercodeNotEqualTo(String value) {
            addCriterion("moduleSuperCode <>", value, "modulesupercode");
            return (Criteria) this;
        }

        public Criteria andModulesupercodeGreaterThan(String value) {
            addCriterion("moduleSuperCode >", value, "modulesupercode");
            return (Criteria) this;
        }

        public Criteria andModulesupercodeGreaterThanOrEqualTo(String value) {
            addCriterion("moduleSuperCode >=", value, "modulesupercode");
            return (Criteria) this;
        }

        public Criteria andModulesupercodeLessThan(String value) {
            addCriterion("moduleSuperCode <", value, "modulesupercode");
            return (Criteria) this;
        }

        public Criteria andModulesupercodeLessThanOrEqualTo(String value) {
            addCriterion("moduleSuperCode <=", value, "modulesupercode");
            return (Criteria) this;
        }

        public Criteria andModulesupercodeLike(String value) {
            addCriterion("moduleSuperCode like", value, "modulesupercode");
            return (Criteria) this;
        }

        public Criteria andModulesupercodeNotLike(String value) {
            addCriterion("moduleSuperCode not like", value, "modulesupercode");
            return (Criteria) this;
        }

        public Criteria andModulesupercodeIn(List<String> values) {
            addCriterion("moduleSuperCode in", values, "modulesupercode");
            return (Criteria) this;
        }

        public Criteria andModulesupercodeNotIn(List<String> values) {
            addCriterion("moduleSuperCode not in", values, "modulesupercode");
            return (Criteria) this;
        }

        public Criteria andModulesupercodeBetween(String value1, String value2) {
            addCriterion("moduleSuperCode between", value1, value2, "modulesupercode");
            return (Criteria) this;
        }

        public Criteria andModulesupercodeNotBetween(String value1, String value2) {
            addCriterion("moduleSuperCode not between", value1, value2, "modulesupercode");
            return (Criteria) this;
        }

        public Criteria andModulepageIsNull() {
            addCriterion("modulePage is null");
            return (Criteria) this;
        }

        public Criteria andModulepageIsNotNull() {
            addCriterion("modulePage is not null");
            return (Criteria) this;
        }

        public Criteria andModulepageEqualTo(String value) {
            addCriterion("modulePage =", value, "modulepage");
            return (Criteria) this;
        }

        public Criteria andModulepageNotEqualTo(String value) {
            addCriterion("modulePage <>", value, "modulepage");
            return (Criteria) this;
        }

        public Criteria andModulepageGreaterThan(String value) {
            addCriterion("modulePage >", value, "modulepage");
            return (Criteria) this;
        }

        public Criteria andModulepageGreaterThanOrEqualTo(String value) {
            addCriterion("modulePage >=", value, "modulepage");
            return (Criteria) this;
        }

        public Criteria andModulepageLessThan(String value) {
            addCriterion("modulePage <", value, "modulepage");
            return (Criteria) this;
        }

        public Criteria andModulepageLessThanOrEqualTo(String value) {
            addCriterion("modulePage <=", value, "modulepage");
            return (Criteria) this;
        }

        public Criteria andModulepageLike(String value) {
            addCriterion("modulePage like", value, "modulepage");
            return (Criteria) this;
        }

        public Criteria andModulepageNotLike(String value) {
            addCriterion("modulePage not like", value, "modulepage");
            return (Criteria) this;
        }

        public Criteria andModulepageIn(List<String> values) {
            addCriterion("modulePage in", values, "modulepage");
            return (Criteria) this;
        }

        public Criteria andModulepageNotIn(List<String> values) {
            addCriterion("modulePage not in", values, "modulepage");
            return (Criteria) this;
        }

        public Criteria andModulepageBetween(String value1, String value2) {
            addCriterion("modulePage between", value1, value2, "modulepage");
            return (Criteria) this;
        }

        public Criteria andModulepageNotBetween(String value1, String value2) {
            addCriterion("modulePage not between", value1, value2, "modulepage");
            return (Criteria) this;
        }

        public Criteria andModulelevelIsNull() {
            addCriterion("moduleLevel is null");
            return (Criteria) this;
        }

        public Criteria andModulelevelIsNotNull() {
            addCriterion("moduleLevel is not null");
            return (Criteria) this;
        }

        public Criteria andModulelevelEqualTo(Integer value) {
            addCriterion("moduleLevel =", value, "modulelevel");
            return (Criteria) this;
        }

        public Criteria andModulelevelNotEqualTo(Integer value) {
            addCriterion("moduleLevel <>", value, "modulelevel");
            return (Criteria) this;
        }

        public Criteria andModulelevelGreaterThan(Integer value) {
            addCriterion("moduleLevel >", value, "modulelevel");
            return (Criteria) this;
        }

        public Criteria andModulelevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("moduleLevel >=", value, "modulelevel");
            return (Criteria) this;
        }

        public Criteria andModulelevelLessThan(Integer value) {
            addCriterion("moduleLevel <", value, "modulelevel");
            return (Criteria) this;
        }

        public Criteria andModulelevelLessThanOrEqualTo(Integer value) {
            addCriterion("moduleLevel <=", value, "modulelevel");
            return (Criteria) this;
        }

        public Criteria andModulelevelIn(List<Integer> values) {
            addCriterion("moduleLevel in", values, "modulelevel");
            return (Criteria) this;
        }

        public Criteria andModulelevelNotIn(List<Integer> values) {
            addCriterion("moduleLevel not in", values, "modulelevel");
            return (Criteria) this;
        }

        public Criteria andModulelevelBetween(Integer value1, Integer value2) {
            addCriterion("moduleLevel between", value1, value2, "modulelevel");
            return (Criteria) this;
        }

        public Criteria andModulelevelNotBetween(Integer value1, Integer value2) {
            addCriterion("moduleLevel not between", value1, value2, "modulelevel");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNull() {
            addCriterion("timestamp is null");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNotNull() {
            addCriterion("timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampEqualTo(Date value) {
            addCriterion("timestamp =", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotEqualTo(Date value) {
            addCriterion("timestamp <>", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThan(Date value) {
            addCriterion("timestamp >", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("timestamp >=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThan(Date value) {
            addCriterion("timestamp <", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThanOrEqualTo(Date value) {
            addCriterion("timestamp <=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampIn(List<Date> values) {
            addCriterion("timestamp in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotIn(List<Date> values) {
            addCriterion("timestamp not in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampBetween(Date value1, Date value2) {
            addCriterion("timestamp between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotBetween(Date value1, Date value2) {
            addCriterion("timestamp not between", value1, value2, "timestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table te_module
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table te_module
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}