package com.circle.vo;

import java.util.Date;

public class TeRoleModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_role_module.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_role_module.roleLabel
     *
     * @mbggenerated
     */
    private String rolelabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_role_module.moduleCode
     *
     * @mbggenerated
     */
    private String modulecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_role_module.mosuleSuperCode
     *
     * @mbggenerated
     */
    private String mosulesupercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_role_module.finds
     *
     * @mbggenerated
     */
    private Boolean finds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_role_module.adds
     *
     * @mbggenerated
     */
    private Boolean adds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_role_module.deletes
     *
     * @mbggenerated
     */
    private Boolean deletes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_role_module.modifys
     *
     * @mbggenerated
     */
    private Boolean modifys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_role_module.timestamp
     *
     * @mbggenerated
     */
    private Date timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_role_module.id
     *
     * @return the value of te_role_module.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_role_module.id
     *
     * @param id the value for te_role_module.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_role_module.roleLabel
     *
     * @return the value of te_role_module.roleLabel
     *
     * @mbggenerated
     */
    public String getRolelabel() {
        return rolelabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_role_module.roleLabel
     *
     * @param rolelabel the value for te_role_module.roleLabel
     *
     * @mbggenerated
     */
    public void setRolelabel(String rolelabel) {
        this.rolelabel = rolelabel == null ? null : rolelabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_role_module.moduleCode
     *
     * @return the value of te_role_module.moduleCode
     *
     * @mbggenerated
     */
    public String getModulecode() {
        return modulecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_role_module.moduleCode
     *
     * @param modulecode the value for te_role_module.moduleCode
     *
     * @mbggenerated
     */
    public void setModulecode(String modulecode) {
        this.modulecode = modulecode == null ? null : modulecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_role_module.mosuleSuperCode
     *
     * @return the value of te_role_module.mosuleSuperCode
     *
     * @mbggenerated
     */
    public String getMosulesupercode() {
        return mosulesupercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_role_module.mosuleSuperCode
     *
     * @param mosulesupercode the value for te_role_module.mosuleSuperCode
     *
     * @mbggenerated
     */
    public void setMosulesupercode(String mosulesupercode) {
        this.mosulesupercode = mosulesupercode == null ? null : mosulesupercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_role_module.finds
     *
     * @return the value of te_role_module.finds
     *
     * @mbggenerated
     */
    public Boolean getFinds() {
        return finds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_role_module.finds
     *
     * @param finds the value for te_role_module.finds
     *
     * @mbggenerated
     */
    public void setFinds(Boolean finds) {
        this.finds = finds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_role_module.adds
     *
     * @return the value of te_role_module.adds
     *
     * @mbggenerated
     */
    public Boolean getAdds() {
        return adds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_role_module.adds
     *
     * @param adds the value for te_role_module.adds
     *
     * @mbggenerated
     */
    public void setAdds(Boolean adds) {
        this.adds = adds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_role_module.deletes
     *
     * @return the value of te_role_module.deletes
     *
     * @mbggenerated
     */
    public Boolean getDeletes() {
        return deletes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_role_module.deletes
     *
     * @param deletes the value for te_role_module.deletes
     *
     * @mbggenerated
     */
    public void setDeletes(Boolean deletes) {
        this.deletes = deletes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_role_module.modifys
     *
     * @return the value of te_role_module.modifys
     *
     * @mbggenerated
     */
    public Boolean getModifys() {
        return modifys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_role_module.modifys
     *
     * @param modifys the value for te_role_module.modifys
     *
     * @mbggenerated
     */
    public void setModifys(Boolean modifys) {
        this.modifys = modifys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_role_module.timestamp
     *
     * @return the value of te_role_module.timestamp
     *
     * @mbggenerated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_role_module.timestamp
     *
     * @param timestamp the value for te_role_module.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}