package com.circle.vo;

import java.util.Date;

public class TeRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_role.roleId
     *
     * @mbggenerated
     */
    private Long roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_role.roleName
     *
     * @mbggenerated
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_role.roleDescription
     *
     * @mbggenerated
     */
    private String roledescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_role.roleLabel
     *
     * @mbggenerated
     */
    private String rolelabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_role.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_role.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column te_role.timestamp
     *
     * @mbggenerated
     */
    private Date timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_role.roleId
     *
     * @return the value of te_role.roleId
     *
     * @mbggenerated
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_role.roleId
     *
     * @param roleid the value for te_role.roleId
     *
     * @mbggenerated
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_role.roleName
     *
     * @return the value of te_role.roleName
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_role.roleName
     *
     * @param rolename the value for te_role.roleName
     *
     * @mbggenerated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_role.roleDescription
     *
     * @return the value of te_role.roleDescription
     *
     * @mbggenerated
     */
    public String getRoledescription() {
        return roledescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_role.roleDescription
     *
     * @param roledescription the value for te_role.roleDescription
     *
     * @mbggenerated
     */
    public void setRoledescription(String roledescription) {
        this.roledescription = roledescription == null ? null : roledescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_role.roleLabel
     *
     * @return the value of te_role.roleLabel
     *
     * @mbggenerated
     */
    public String getRolelabel() {
        return rolelabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_role.roleLabel
     *
     * @param rolelabel the value for te_role.roleLabel
     *
     * @mbggenerated
     */
    public void setRolelabel(String rolelabel) {
        this.rolelabel = rolelabel == null ? null : rolelabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_role.createTime
     *
     * @return the value of te_role.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_role.createTime
     *
     * @param createtime the value for te_role.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_role.creator
     *
     * @return the value of te_role.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_role.creator
     *
     * @param creator the value for te_role.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column te_role.timestamp
     *
     * @return the value of te_role.timestamp
     *
     * @mbggenerated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column te_role.timestamp
     *
     * @param timestamp the value for te_role.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}