package com.circle.vo;

import java.util.Date;

public class WebSiteInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_site_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_site_info.info
     *
     * @mbggenerated
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_site_info.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_site_info.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_site_info.film_id
     *
     * @mbggenerated
     */
    private Integer filmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_site_info.web_site_id
     *
     * @mbggenerated
     */
    private Integer webSiteId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_site_info.id
     *
     * @return the value of web_site_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_site_info.id
     *
     * @param id the value for web_site_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_site_info.info
     *
     * @return the value of web_site_info.info
     *
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_site_info.info
     *
     * @param info the value for web_site_info.info
     *
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_site_info.url
     *
     * @return the value of web_site_info.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_site_info.url
     *
     * @param url the value for web_site_info.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_site_info.createTime
     *
     * @return the value of web_site_info.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_site_info.createTime
     *
     * @param createtime the value for web_site_info.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_site_info.film_id
     *
     * @return the value of web_site_info.film_id
     *
     * @mbggenerated
     */
    public Integer getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_site_info.film_id
     *
     * @param filmId the value for web_site_info.film_id
     *
     * @mbggenerated
     */
    public void setFilmId(Integer filmId) {
        this.filmId = filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_site_info.web_site_id
     *
     * @return the value of web_site_info.web_site_id
     *
     * @mbggenerated
     */
    public Integer getWebSiteId() {
        return webSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_site_info.web_site_id
     *
     * @param webSiteId the value for web_site_info.web_site_id
     *
     * @mbggenerated
     */
    public void setWebSiteId(Integer webSiteId) {
        this.webSiteId = webSiteId;
    }
}